package ssta.pe.p041_050;

/**
 * Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten
 * pentagonal numbers are:
 * <p>
 * 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 * <p>
 * It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
 * 70 − 22 = 48, is not pentagonal.
 * <p>
 * Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
 * difference are pentagonal and D = |Pk − Pj| is minimised; what is the value
 * of D?
 * <p>
 * Created by ssta on 02/01/16.
 */
class Problem44 {

  public static void main(String[] args) {

    Problem44 p = new Problem44();
    System.out.println(p.solve());
  }


  /**
   * Returns the nth pentagonal number
   */
  private int pent(int n) {
    return n * (3 * n - 1) / 2;
  }

  /**
   * Returns true IFF n is pentagonal
   */
  private boolean isPentagonal(int n) {
    double t = (Math.sqrt(1 + 24 * n) + 1.0) / 6.0;
    return t == (int) t;
  }

  public String solve() {
    /* for reasons I don't understand the first one found is the "correct" one
     * so we do a nested loop until we find one that fits the criteria.
     *
     * 5000 is an arbitrary upper bound (that we don't reach, so it doesn't
     * matter - actually the right answer is where i=2167 and j=1020)
     */
    for (int i = 2; i < 5000; i++) {
      int penti = pent(i);
      // start at pent(i) and go down looking for sum/diff that are both
      // pentagonal
      for (int j = i - 1; j > 0; j--) {
        int pentj = pent(j);
        if (isPentagonal(penti - pentj) && isPentagonal(pent(i) + pent(j))) {
          return String.valueOf(penti - pentj);
        }
      }
    }

    return String.valueOf(0);
  }
}
