package ssta.pe.P021_030;

import java.util.Set;
import java.util.TreeSet;

/**
 * Created by ssta on 03/05/15.
 */
class Problem29 {

  /**
   * Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:
   * <p>
   * 22=4, 23=8, 24=16, 25=32
   * 32=9, 33=27, 34=81, 35=243
   * 42=16, 43=64, 44=256, 45=1024
   * 52=25, 53=125, 54=625, 55=3125
   * If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:
   * <p>
   * 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
   * <p>
   * How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
   */
  public String solve() {
    // brute force and ugly.  There must be some analytical method, but I
    // don't know how...maybe something around distinct factors...
    Set<Double> powers = new TreeSet<>();
    final int MAX = 100;
    for (int a = 2; a <= MAX; a++) {
      for (int b = 2; b <= MAX; b++) {
        double d = Math.pow(a, b);
        powers.add(d);
      }
    }

    return String.valueOf(powers.size());
  }
}
