package ssta.pe.p1_10;

/**
 * Created by ssta on 03/05/15.
 */
public class Problem2 {
  static final long MAX = 4000000;

  /**
   * Each new term in the Fibonacci sequence is generated by adding the previous
   * two terms. By starting with 1 and 2, the first 10 terms will be:
   * <p>
   * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
   * <p>
   * By considering the terms in the Fibonacci sequence whose values do not exceed
   * four million, find the sum of the even-valued terms.
   * <p>
   * Created by ssta on 03/05/15.
   */
  public String solve() {
    int a = 0;
    int b = 1;
    int sum = 0;
    do {
      // if a is even, add it to sum;
      if (a % 2 == 0) { sum += a; }

      int t = b;
      b = a;
      a = t + b;

    } while (a < MAX);
    return String.valueOf(sum);
  }
}
